baseURL = "/"
title = "Spectral"
languageCode = "pt-br"
defaultContentLanguage = "pt"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Gerfy"
favicon = true
copyright = "Gerfy"
description = 'Software Developer<br/>Creating the future of technology<br />'
startbuttonText = "Github"
startbuttonLink = "https://github.com/Gerfy1"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["banner.jpg"]


[taxonomies]
    tag = ""
    category = ""
    series = ""

[params.one]
enable = true
title = 'Atualmente graduando em Analise e Desenvolvimento de Sistemas pela UNIESP(IESP)'
body = '''
Estou focado em aprimorar minhas habilidades em desenvolvimento de sistemas e softwares. Procuro absorver conhecimento e experiência prática para construir uma base sólida nesta área dinâmica e desafiadora. Estou entusiasmado com as oportunidades de aprendizado e crescimento no qual os estudos oferecem e espero aplicar o que aprendi em todos os projetos.'''

[[params.one.icon]]
icon = "fa-face-laugh-beam"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/Code-typing-bro-_1_-resize.png"
img_alt = "blurry background: white/grey"
title = 'FIPE APP<br/>'
body = '''
O FipeApp é uma aplicação Java que permite aos usuários consultar preços médios de veículos com base na Tabela Fipe. A Tabela Fipe é uma referência importante para negociações e avaliações de veículos no mercado nacional.

A aplicação permite consultar preços médios de acordo com o mês e ano de referência. Você também pode pesquisar por marca, modelo e ano do veículo desejado.

Tecnologias utilizadas: Java, API, Spring, Maven.

Link do projeto: (https://github.com/Gerfy1/FipeAPP)
'''
[[params.two.section]]
img = "img/Hand-coding-bro-_1_-resize.png"
title = 'Med API'
body = '''
Este projeto desenvolve uma API REST para gerenciar operações em um consultório médico, abrangendo tanto o lado do cliente quanto do servidor, e integrando ambos. 

Este projeto visa demonstrar a aplicação prática dessas tecnologias e práticas no contexto de desenvolvimento de APIs RESTful para aplicações corporativas.

Tecnologias utilizadas: Java, DTO, Banco de Dados, Flyway, Requisições HTTP, Beans, Spring Security, JWT, Spring Doc, Fluxo Given/When/Then, JUnit & AssetJ, Mockito.

Link do projeto: (https://github.com/Gerfy1/MedAPI)
'''


[[params.two.section]]
img = "img/Coding-bro-_1_ -resize.png"
title = 'Forum HUB'
body = '''
O Fórum Hub é um desafio proposto na conclusão do programa Oracle ONE. O projeto visa consolidar conhecimentos e replicar a parte de Back-End de um fórum, focando em práticas de desenvolvimento e integração de sistemas.

As regras de negócio determinam que apenas usuários cadastrados podem criar, editar ou deletar tópicos e respostas. A autenticação é feita com tokens Bearer, e somente o autor pode modificar seu conteúdo. Cada tópico deve ter um título, uma mensagem, estar vinculado a um curso e incluir uma data de criação.

Tecnologias utilizadas: Java, Spring, MySQL, Hibernate, JWT, Lombok, Flyway, Spring Security, Spring Data JPA, SpringDoc.

Link do projeto: (https://github.com/Gerfy1/ForumHub)
'''

[params.three]
enable = true
title = 'Habilidades e pontos principais'
body = '''
Pensamento crítico, adaptabilidade, criatividade, aprendizado contínuo e flexibilidade cognitiva são algumas das minhas soft skills. Conheça um pouco mais sobre elas abaixo.
'''

[[params.three.feature]]
icon = "fa-comments"
title = "Comunicação eficaz e transparência"
body = "Capacidade de se comunicar de forma clara, transparente e proativa com clientes, colegas e gerentes de projeto. Capacidade de entender as necessidades do cliente, gerenciar expectativas e resolver problemas de forma colaborativa."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Solução criativa em resolução de problemas"
body = "Capacidade de pensar de forma inovadora e encontrar soluções criativas para desafios complexos de desenvolvimento de software. Demonstra capacidade de inovar e se adaptar a diferentes situações."

[[params.three.feature]]
icon = "solid fa-code"
title = "Compromisso com prazos e qualidade"
body = "Capacidade comprovada de cumprir prazos e entregar projetos de alta qualidade dentro do prazo estabelecido. Confiança em atender às expectativas do cliente ou empregador."

[[params.three.feature]]
icon = "solid fa-user"
title = "Foco na experiência do usuário"
body = "Compromisso em criar produtos centrados no usuário, garantindo que sejam intuitivos, acessíveis e proporcionem uma excelente experiência ao usuário final."

[[params.three.feature]]
icon = "fa-heart"
title = "Compromisso com o desenvolvimento de software"
body = "Compromisso genuíno com o desenvolvimento de software e tecnologia, demonstrando vontade de superar expectativas e entregar resultados excepcionais para clientes e empregadores."

[[params.three.feature]]
icon = "fa-handshake"
title = "Colaboração e trabalho em equipe"
body = "Capacidade de colaborar de forma eficaz com colegas, promovendo um ambiente de trabalho colaborativo. Capacidade de compartilhar ideias, respeitar opiniões e trabalhar em conjunto para alcançar objetivos comuns."

[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Conheça-me"
special = false

[params.contact]
enable = false
phone = "+5583988442527"
email = "gerfynlol@gmail.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = "Gerfy1"
facebook = "in/geraldoaafilho"
youtube = ""
instagram = "codedbygerfy"
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"

[languages.pt]
languageName = "Português"
weight = 2
